cphp56:
  image: mycentos/php-5.6
  hostname: php-5-6
  volumes:
    - ~/Documents/wwwroot:/home/vagrant/wwwroot
  expose:
    - "9000"

cnginx:
  image: mycentos/nginx
  hostname: nginx-1-10-1
  volumes:
    - ~/Documents/wwwroot:/home/vagrant/wwwroot
    - ~/Documents/wwwroot/web/dockerfile/centos/nginx-php/conf.d:/etc/nginx/conf.d
  ports:
    - "80:80"
  links:
    - cphp56

#docker run -d --name cphp56 -h php-5-6 -v ~/Documents/wwwroot:/home/vagrant/wwwroot mycentos/php-5.6

#docker run -d -p 80:80 --name inginx -h nginx-1-10-1 -v ~/Documents/wwwroot:/home/vagrant/wwwroot -v ~/Documents/wwwroot/web/dockerfile/nginx-php/conf.d:/etc/nginx/conf.d --link cphp56:cphp56 mycentos/nginx
